### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by scriptex** [amondnet/now-deployment#55]
Hi, I have a scheduled github action which deploys my code everyday at noon UTC.
So far so good but today it threw a weird error - something which I couldn't reproduce locally:
```sh
Error! An unexpected error occurred in inspect: TypeError: Cannot read property 'split' of undefined
    at /usr/local/lib/node_modules/vercel/dist/index.js:2:650065
    at Array.reduce (<anonymous>)
    at A (/usr/local/lib/node_modules/vercel/dist/index.js:2:650029)
    at inspect_main (/usr/local/lib/node_modules/vercel/dist/index.js:2:655310)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at he (/usr/local/lib/node_modules/vercel/dist/index.js:2:375059)
```
Do you have any idea if this error is caused by Vercel or by your action?

**Comment by jackguoAtJogg** [comment]
I have the same error as well.

**Comment by SmileJayden** [comment]
Me too.
From yesterday

```
Error! An unexpected error occurred in inspect: TypeError: Cannot read property 'split' of undefined
    at /usr/local/lib/node_modules/vercel/dist/index.js:2:650065
    at Array.reduce (<anonymous>)
    at A (/usr/local/lib/node_modules/vercel/dist/index.js:2:650029)
    at inspect_main (/usr/local/lib/node_modules/vercel/dist/index.js:2:655310)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at he (/usr/local/lib/node_modules/vercel/dist/index.js:2:375059)
```

**Comment by jackguoAtJogg** [comment]
I tried to switch to vercel-action but they have the same error as well. 
I hope this can be fixed soon.

https://github.com/amondnet/vercel-action/issues/28

**Comment by lukasholzer** [comment]
We encounter the same error regardless of with the vercel or old now action.
Hope this can get fixed soon!

**Comment by EvanLovely** [comment]
Yep, we're having the same problem using the `vercel-action` GitHub Action: https://github.com/amondnet/vercel-action/issues/27 I've got a string of troubleshooting notes going on over there if anyone is interested.

**Comment by scriptex** [comment]
It looks like the action runs and completes properly since yesterday. Maybe Vercel updated/fixed something on their side?
Anyone still experiencing issues?
I will give it one more day and then I will close this issue.

**Comment by jackguoAtJogg** [comment]
Yep, looks like is working now.

**Comment by amondnet** [comment]
https://github.com/amondnet/vercel-action/pull/29

**Comment by scriptex** [comment]
Looks like it's fixed. Closing the issue 😄
